# Generated by Django 5.1.2 on 2024-10-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_fee', models.IntegerField()),
                ('timings', models.TimeField()),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('instructor', models.CharField(max_length=100)),
            ],
        ),
    ]
